(function(){
'use strict';
const VB_BASE='https://gqaydqnzhoqihbzimify.supabase.co',VB_KEY='sb_publishable_QyWjseNpmoQOsqcFAq5_7w_3t4_b8GK',VB_ADMIN='ttjtioc.ha.muhyc@gmail.com',VB_STORE='vb-admin-session';
const loginView=document.getElementById('loginView'),adminView=document.getElementById('adminView');
let token=localStorage.getItem(VB_STORE)||'';
const esc=v=>{const d=document.createElement('div');d.textContent=v??'';return d.innerHTML},fmt=v=>new Date(v).toLocaleString('ru-RU');
async function request(path,{method='GET',body,raw=false,headers={}}={}){const h={apikey:VB_KEY,...headers};if(token)h.Authorization='Bearer '+token;if(!raw)h['content-type']='application/json';const r=await fetch(VB_BASE+path,{method,headers:h,body:body===undefined?undefined:(raw?body:JSON.stringify(body))});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw new Error(data?.msg||data?.message||data?.error_description||data?.hint||'Ошибка запроса');return data}
async function showAdmin(){loginView.hidden=true;adminView.hidden=false;await Promise.all([loadIdeas(),loadQuestions(),loadPolls()])}
async function restore(){if(!token)return;try{const u=await request('/auth/v1/user');if(u.email?.toLowerCase()===VB_ADMIN)await showAdmin();else throw new Error('Нет доступа')}catch{token='';localStorage.removeItem(VB_STORE)}}
document.getElementById('loginForm').addEventListener('submit',async e=>{e.preventDefault();const s=document.getElementById('loginStatus'),button=e.target.querySelector('button');s.textContent='Входим…';button.disabled=true;try{const data=await request('/auth/v1/token?grant_type=password',{method:'POST',body:{email:VB_ADMIN,password:document.getElementById('password').value}});if(data.user?.email?.toLowerCase()!==VB_ADMIN)throw new Error('У этой учётной записи нет доступа');token=data.access_token;localStorage.setItem(VB_STORE,token);s.textContent='';await showAdmin()}catch(err){s.textContent='Ошибка входа: '+err.message}finally{button.disabled=false}});
document.getElementById('logoutBtn').addEventListener('click',()=>{token='';localStorage.removeItem(VB_STORE);location.reload()});
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.pane').forEach(x=>x.classList.toggle('active',x.id===b.dataset.tab+'Pane'))}));
document.querySelectorAll('[data-refresh]').forEach(b=>b.addEventListener('click',()=>({ideas:loadIdeas,questions:loadQuestions,polls:loadPolls})[b.dataset.refresh]()));
async function loadIdeas(){const box=document.getElementById('ideasList');box.innerHTML='<div class="empty">Загрузка…</div>';try{const data=await request('/rest/v1/ideas?select=*&order=created_at.desc');box.innerHTML=data.length?data.map(i=>`<article class="card" data-idea="${i.id}"><div class="meta">${fmt(i.created_at)} · <span class="badge">${esc(i.status)}</span> · ${esc(i.visibility)}</div><div class="grid"><div class="field"><label>Никнейм</label><input data-field="nickname" value="${esc(i.nickname)}"></div><div class="field"><label>Категория</label><input data-field="category" value="${esc(i.category)}"></div></div><div class="field"><label>Предложение</label><textarea data-field="body">${esc(i.body)}</textarea></div><div class="field"><label>Ответ разработчика</label><textarea data-field="developer_reply">${esc(i.developer_reply||'')}</textarea></div><div class="actions"><button class="btn small" data-action="save-idea">Сохранить</button><button class="btn small primary" data-action="publish-idea">Опубликовать</button><button class="btn small" data-action="reject-idea">Отклонить</button><button class="btn small danger" data-action="delete-idea">Удалить</button></div><div class="status"></div></article>`).join(''):'<div class="empty">Предложений пока нет.</div>'}catch(e){box.innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}
document.getElementById('ideasList').addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const c=b.closest('[data-idea]'),id=c.dataset.idea,out=c.querySelector('.status'),a=b.dataset.action;if(a==='delete-idea'&&!confirm('Удалить предложение?'))return;try{if(a==='delete-idea')await request('/rest/v1/ideas?id=eq.'+id,{method:'DELETE'});else{const p={nickname:c.querySelector('[data-field=nickname]').value.trim(),category:c.querySelector('[data-field=category]').value.trim(),body:c.querySelector('[data-field=body]').value.trim(),developer_reply:c.querySelector('[data-field=developer_reply]').value.trim()||null,updated_at:new Date().toISOString()};if(a==='publish-idea')p.status='published';if(a==='reject-idea')p.status='rejected';await request('/rest/v1/ideas?id=eq.'+id,{method:'PATCH',body:p})}out.textContent='Готово';if(a!=='save-idea')loadIdeas()}catch(err){out.textContent=err.message}});
async function loadQuestions(){const box=document.getElementById('questionsList');box.innerHTML='<div class="empty">Загрузка…</div>';try{const data=await request('/rest/v1/questions?select=*&order=created_at.desc');box.innerHTML=data.length?data.map(q=>`<article class="card" data-question="${q.id}"><div class="meta">${fmt(q.created_at)} · <span class="badge">${esc(q.status)}</span></div><div class="field"><label>Никнейм</label><input data-field="nickname" value="${esc(q.nickname)}"></div><div class="field"><label>Вопрос</label><textarea data-field="question">${esc(q.question)}</textarea></div><div class="field"><label>Ответ</label><textarea data-field="answer">${esc(q.answer||'')}</textarea></div><div class="actions"><button class="btn small" data-action="save-question">Сохранить</button><button class="btn small primary" data-action="publish-question">Опубликовать ответ</button><button class="btn small" data-action="reject-question">Отклонить</button><button class="btn small danger" data-action="delete-question">Удалить</button></div><div class="status"></div></article>`).join(''):'<div class="empty">Вопросов пока нет.</div>'}catch(e){box.innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}
document.getElementById('questionsList').addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const c=b.closest('[data-question]'),id=c.dataset.question,out=c.querySelector('.status'),a=b.dataset.action;if(a==='delete-question'&&!confirm('Удалить вопрос?'))return;try{if(a==='delete-question')await request('/rest/v1/questions?id=eq.'+id,{method:'DELETE'});else{const p={nickname:c.querySelector('[data-field=nickname]').value.trim(),question:c.querySelector('[data-field=question]').value.trim(),answer:c.querySelector('[data-field=answer]').value.trim()||null};if(a==='publish-question'){if(!p.answer)throw new Error('Сначала напишите ответ');p.status='published';p.answered_at=new Date().toISOString()}if(a==='reject-question')p.status='rejected';await request('/rest/v1/questions?id=eq.'+id,{method:'PATCH',body:p})}out.textContent='Готово';if(a!=='save-question')loadQuestions()}catch(err){out.textContent=err.message}});
document.getElementById('pollForm').addEventListener('submit',async e=>{e.preventDefault();const out=document.getElementById('pollStatus'),labels=document.getElementById('pollOptions').value.split('\n').map(x=>x.trim()).filter(Boolean),button=e.target.querySelector('button');if(labels.length<2){out.textContent='Нужно минимум два варианта.';return}button.disabled=true;out.textContent='Создаём…';try{let image_url=null;const file=document.getElementById('pollImage').files[0];if(file){const name=crypto.randomUUID()+'-'+file.name.replace(/[^a-zA-Z0-9._-]/g,'_');await request('/storage/v1/object/poll-images/'+name,{method:'POST',body:file,raw:true,headers:{'content-type':file.type||'application/octet-stream'}});image_url=VB_BASE+'/storage/v1/object/public/poll-images/'+name}const created=await request('/rest/v1/polls',{method:'POST',headers:{Prefer:'return=representation'},body:{title:document.getElementById('pollTitle').value.trim(),body:document.getElementById('pollBody').value.trim()||null,image_url,status:'published'}});const id=created[0].id;await request('/rest/v1/poll_options',{method:'POST',body:labels.map((label,position)=>({poll_id:id,label,position}))});e.target.reset();out.textContent='Опрос опубликован.';loadPolls()}catch(err){out.textContent=err.message}finally{button.disabled=false}});
async function loadPolls(){const box=document.getElementById('pollsList');box.innerHTML='<div class="empty">Загрузка…</div>';try{const data=await request('/rest/v1/polls?select=*,poll_options(id,label,position)&order=created_at.desc');box.innerHTML=data.length?data.map(p=>`<article class="card" data-poll="${p.id}"><div class="meta">${fmt(p.created_at)} · <span class="badge">${esc(p.status)}</span></div><h3>${esc(p.title)}</h3><div class="poll-options">${(p.poll_options||[]).sort((a,b)=>a.position-b.position).map(o=>'• '+esc(o.label)).join('<br>')}</div><div class="actions"><button class="btn small primary" data-poll-action="published">Опубликовать</button><button class="btn small" data-poll-action="closed">Закрыть</button><button class="btn small" data-poll-action="draft">Скрыть</button><button class="btn small danger" data-poll-action="delete">Удалить</button></div><div class="status"></div></article>`).join(''):'<div class="empty">Опросов пока нет.</div>'}catch(e){box.innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}
document.getElementById('pollsList').addEventListener('click',async e=>{const b=e.target.closest('[data-poll-action]');if(!b)return;const c=b.closest('[data-poll]'),id=c.dataset.poll,a=b.dataset.pollAction;if(a==='delete'&&!confirm('Удалить опрос и голоса?'))return;try{await request('/rest/v1/polls?id=eq.'+id,{method:a==='delete'?'DELETE':'PATCH',body:a==='delete'?undefined:{status:a}});loadPolls()}catch(err){c.querySelector('.status').textContent=err.message}});
restore();
})();
